---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-keys
  namespace: stage
data:
  token: U3M2V3hGdWlBbE1ieHRmM3FYTGFjaHRI
---
apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: stage
  labels:
    app: vault
spec:
  containers:
  - name: vault
    image: vault:1.10.3
    ports:
    - name: vault-port
      containerPort: 8200
      protocol: TCP
    env:
    - name: VAULT_DEV_ROOT_TOKEN_ID
      valueFrom:
        secretKeyRef:
          name: vault-keys
          key: token
    - name: VAULT_DEV_LISTEN_ADDRESS
      value: 0.0.0.0:8200
---
apiVersion: v1
kind: Service
metadata:  
  name: vault-nodeport-service
  namespace: stage
spec:
  selector:    
    app: vault
  type: NodePort
  ports:  
  - name: vault-port
    port: 8200
    targetPort: 8200
    nodePort: 30200
    protocol: TCP