filebeat.inputs:
  - type: filestream
    paths:
      - "/opt/test/log/*/*.log"
      - "/var/log/*.log"

processors:
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

output.logstash:
  hosts: ["logstash:5046"]

# output.console:
#   enabled: true

logging.json: true
logging.metrics.enabled: false
