version: '3'
services:
  prometheus:
    image: bitnami/prometheus:2.32.1-debian-10-r3
    container_name: prometheus
    privileged: false
    volumes:
      - ./prometheus:/opt/bitnami/prometheus/data
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - 9090:9090
    expose:
      - 9090
      - 9093
    depends_on:
      - node-exporter
    networks:
      - prom-stack-net

  node-exporter:
    image: bitnami/node-exporter:1.3.1-debian-10-r16
    container_name: node-exporter
    privileged: false
    networks:
      - prom-stack-net

  grafana:
    image: bitnami/grafana:8.3.3-debian-10-r7
    container_name: grafana
    privileged: false
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "!QAZ2wsx"
      GF_RENDERING_SERVER_URL: "http://grafana-image-renderer:8080/render"
      GF_RENDERING_CALLBACK_URL: "http://grafana:3000/"
    depends_on:
      - prometheus
      - grafana-image-renderer
    networks:
      - prom-stack-net

  grafana-image-renderer:
    image: bitnami/grafana-image-renderer:3.3.0-debian-10-r31
    container_name: grafana-image-renderer
    privileged: false
    ports:
      - 8080:8080
    environment:
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 8080
      ENABLE_METRICS: "true"
    networks:
      - prom-stack-net

networks:
  prom-stack-net:
    driver: bridge
