{
 "title": "Netology",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\",job=\"node_exporter_1\"}[5m])) by (instance)) * 100",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "node_load1{job=\"node_exporter_1\"}",
     "legendFormat": "LA1"
    },
    {
     "expr": "node_load5{job=\"node_exporter_1\"}",
     "legendFormat": "LA5"
    },
    {
     "expr": "node_load15{job=\"node_exporter_1\"}",
     "legendFormat": "LA15"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"node_exporter_1\"}) / 1073741824",
     "legendFormat": "Mem total"
    },
    {
     "expr": "(node_memory_Active_bytes{job=\"node_exporter_1\"}) / 1073741824",
     "legendFormat": "Mem usage"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(avg by(instance)(node_filesystem_size_bytes{job=\"node_exporter_1\"})) / 1073741824",
     "legendFormat": "Space total"
    },
    {
     "expr": "(avg by(instance)(node_filesystem_avail_bytes{job=\"node_exporter_1\"})) / 1073741824",
     "legendFormat": "Space available"
    }
   ]
  }
 ]
}