---
apiVersion: v1
kind: Namespace
metadata:
  name: stage
---
apiVersion: v1
kind: Pod
metadata:
  name: pods-with-secret
  namespace: stage
spec:
  restartPolicy: Never
  volumes:
  - name: certs-volume
    secret:
      secretName: domain-cert
  containers:
  - name: nginx-pod
    image: bitnami/nginx:latest
    volumeMounts:
    - name: certs-volume
      readOnly: true
      mountPath: "/bitnami/certs"
    env: 
    - name: TLS_CRT
      valueFrom:
        secretKeyRef:
          name: domain-cert
          key: tls.crt
    - name: TLS_KEY
      valueFrom:
        secretKeyRef:
          name: domain-cert
          key: tls.key
