version: '3'
services:
  elasticsearch-hot:
    image: bitnami/elasticsearch:7.16.2-debian-10-r9
    container_name: elasticsearch-hot
    volumes:
      - ./elasticsearch-hot/data:/opt/bitnami/elasticsearch/data:Z
      - ./elasticsearch-hot/elasticsearch.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml:Z
    expose:
      - 9200
      - 9300
    networks:
      - elk-stack-net

  elasticsearch-warm:
    image: bitnami/elasticsearch:7.16.2-debian-10-r9
    container_name: elasticsearch-warm
    volumes:
      - ./elasticsearch-warm/data:/opt/bitnami/elasticsearch/data:Z
      - ./elasticsearch-warm/elasticsearch.yml:/opt/bitnami/elasticsearch/config/elasticsearch.yml:Z
    expose:
      - 9200
      - 9300
    networks:
      - elk-stack-net

  logstash:
    image: bitnami/logstash:7.16.2-debian-10-r7
    container_name: logstash
    environment:
      - LOGSTASH_PIPELINE_CONF_FILENAME=logstash.conf
    volumes:
      - ./logstash/pipeline:/bitnami/logstash/pipeline:Z
    expose:
      - 5046
    depends_on:
      - elasticsearch-hot
      - elasticsearch-warm
    networks:
      - elk-stack-net

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeat
    privileged: true
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:Z
      - /var/log:/opt/test/log:z
    depends_on:
      - logstash
    networks:
      - elk-stack-net

  kibana:
    image: bitnami/kibana:7.16.2-debian-10-r14
    container_name: kibana
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch-hot
    depends_on:
      - elasticsearch-hot
      - elasticsearch-warm
    ports:
      - 5601:5601
    expose:
      - 5601
    networks:
      - elk-stack-net

networks:
  elk-stack-net:
    driver: bridge
